import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { SmartCardStatus } from '@/modules/smart-cards/enums/smart-card-status.enum';
import { StudentProfile } from '@/modules/students/entities/student-profile.entity';

@Entity('smart_cards')
export class SmartCard {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @Column({ type: 'uuid', name: 'student_profile_id' })
  studentProfileId: string;

  @ManyToOne(() => StudentProfile, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'student_profile_id' })
  studentProfile: StudentProfile;

  /** The card number as issued by the external Student Smart Card system — never generated by SSC. */
  @Index({ unique: true })
  @Column({ type: 'varchar', length: 64, name: 'card_number' })
  cardNumber: string;

  @Index({ unique: true })
  @Column({ type: 'varchar', length: 64, name: 'qr_token' })
  qrToken: string;

  @Column({ type: 'enum', enum: SmartCardStatus, default: SmartCardStatus.ACTIVE })
  status: SmartCardStatus;

  @Column({ type: 'uuid', name: 'replaces_card_id', nullable: true })
  replacesCardId: string | null;

  @Column({ type: 'timestamptz', name: 'issued_at' })
  issuedAt: Date;

  @Column({ type: 'timestamptz', name: 'expires_at' })
  expiresAt: Date;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
